//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.15 at 07:23:39 AM EDT 
//


package org.mitre.ptmatchadapter.fril.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="left-data-source">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="params">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="param" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="row-model">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="column" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="empty-values" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="params" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="column" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="converter" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="preprocessing">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="deduplication">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="deduplication-condition">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="condition" maxOccurs="unbounded">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="params" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                         &lt;/sequence>
 *                                                         &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                         &lt;attribute name="column" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                         &lt;attribute name="weight" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="acceptance-level" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="hashing-function">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;attribute name="columns" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="hash" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="minus-file">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;attribute name="file" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="dedupe-file">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;attribute name="file" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="deduplication" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "leftDataSource"
})
@XmlRootElement(name = "configuration")
public class Configuration {

    @XmlElement(name = "left-data-source", required = true)
    protected Configuration.LeftDataSource leftDataSource;
    @XmlAttribute(name = "deduplication")
    protected Boolean deduplication;

    /**
     * Gets the value of the leftDataSource property.
     * 
     * @return
     *     possible object is
     *     {@link Configuration.LeftDataSource }
     *     
     */
    public Configuration.LeftDataSource getLeftDataSource() {
        return leftDataSource;
    }

    /**
     * Sets the value of the leftDataSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configuration.LeftDataSource }
     *     
     */
    public void setLeftDataSource(Configuration.LeftDataSource value) {
        this.leftDataSource = value;
    }

    /**
     * Gets the value of the deduplication property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDeduplication() {
        return deduplication;
    }

    /**
     * Sets the value of the deduplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeduplication(Boolean value) {
        this.deduplication = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="params">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="param" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="row-model">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="column" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="empty-values" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="params" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="column" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="converter" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="preprocessing">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="deduplication">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="deduplication-condition">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="condition" maxOccurs="unbounded">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="params" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                               &lt;/sequence>
     *                                               &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                               &lt;attribute name="column" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                               &lt;attribute name="weight" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                     &lt;attribute name="acceptance-level" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="hashing-function">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;attribute name="columns" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="hash" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="minus-file">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;attribute name="file" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="dedupe-file">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;attribute name="file" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "params",
        "rowModel",
        "preprocessing"
    })
    public static class LeftDataSource {

        @XmlElement(required = true)
        protected Configuration.LeftDataSource.Params params;
        @XmlElement(name = "row-model", required = true)
        protected Configuration.LeftDataSource.RowModel rowModel;
        @XmlElement(required = true)
        protected Configuration.LeftDataSource.Preprocessing preprocessing;
        @XmlAttribute(name = "class")
        protected String clazz;
        @XmlAttribute(name = "name")
        protected String name;

        /**
         * Gets the value of the params property.
         * 
         * @return
         *     possible object is
         *     {@link Configuration.LeftDataSource.Params }
         *     
         */
        public Configuration.LeftDataSource.Params getParams() {
            return params;
        }

        /**
         * Sets the value of the params property.
         * 
         * @param value
         *     allowed object is
         *     {@link Configuration.LeftDataSource.Params }
         *     
         */
        public void setParams(Configuration.LeftDataSource.Params value) {
            this.params = value;
        }

        /**
         * Gets the value of the rowModel property.
         * 
         * @return
         *     possible object is
         *     {@link Configuration.LeftDataSource.RowModel }
         *     
         */
        public Configuration.LeftDataSource.RowModel getRowModel() {
            return rowModel;
        }

        /**
         * Sets the value of the rowModel property.
         * 
         * @param value
         *     allowed object is
         *     {@link Configuration.LeftDataSource.RowModel }
         *     
         */
        public void setRowModel(Configuration.LeftDataSource.RowModel value) {
            this.rowModel = value;
        }

        /**
         * Gets the value of the preprocessing property.
         * 
         * @return
         *     possible object is
         *     {@link Configuration.LeftDataSource.Preprocessing }
         *     
         */
        public Configuration.LeftDataSource.Preprocessing getPreprocessing() {
            return preprocessing;
        }

        /**
         * Sets the value of the preprocessing property.
         * 
         * @param value
         *     allowed object is
         *     {@link Configuration.LeftDataSource.Preprocessing }
         *     
         */
        public void setPreprocessing(Configuration.LeftDataSource.Preprocessing value) {
            this.preprocessing = value;
        }

        /**
         * Gets the value of the clazz property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClazz() {
            return clazz;
        }

        /**
         * Sets the value of the clazz property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClazz(String value) {
            this.clazz = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="param" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "param"
        })
        public static class Params {

            @XmlElement(required = true)
            protected List<Configuration.LeftDataSource.Params.Param> param;

            /**
             * Gets the value of the param property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the param property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getParam().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Configuration.LeftDataSource.Params.Param }
             * 
             * 
             */
            public List<Configuration.LeftDataSource.Params.Param> getParam() {
                if (param == null) {
                    param = new ArrayList<Configuration.LeftDataSource.Params.Param>();
                }
                return this.param;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Param {

                @XmlAttribute(name = "name")
                protected String name;
                @XmlAttribute(name = "value")
                protected String value;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="deduplication">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="deduplication-condition">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="condition" maxOccurs="unbounded">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="params" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                     &lt;/sequence>
         *                                     &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                     &lt;attribute name="column" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                     &lt;attribute name="weight" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                           &lt;attribute name="acceptance-level" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="hashing-function">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;attribute name="columns" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="hash" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="minus-file">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;attribute name="file" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="dedupe-file">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;attribute name="file" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "deduplication"
        })
        public static class Preprocessing {

            @XmlElement(required = true)
            protected Configuration.LeftDataSource.Preprocessing.Deduplication deduplication;

            /**
             * Gets the value of the deduplication property.
             * 
             * @return
             *     possible object is
             *     {@link Configuration.LeftDataSource.Preprocessing.Deduplication }
             *     
             */
            public Configuration.LeftDataSource.Preprocessing.Deduplication getDeduplication() {
                return deduplication;
            }

            /**
             * Sets the value of the deduplication property.
             * 
             * @param value
             *     allowed object is
             *     {@link Configuration.LeftDataSource.Preprocessing.Deduplication }
             *     
             */
            public void setDeduplication(Configuration.LeftDataSource.Preprocessing.Deduplication value) {
                this.deduplication = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="deduplication-condition">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="condition" maxOccurs="unbounded">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="params" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                           &lt;/sequence>
             *                           &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                           &lt;attribute name="column" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                           &lt;attribute name="weight" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *                 &lt;attribute name="acceptance-level" type="{http://www.w3.org/2001/XMLSchema}int" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="hashing-function">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;attribute name="columns" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="hash" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="minus-file">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;attribute name="file" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="dedupe-file">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;attribute name="file" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "deduplicationCondition",
                "hashingFunction",
                "minusFile",
                "dedupeFile"
            })
            public static class Deduplication {

                @XmlElement(name = "deduplication-condition", required = true)
                protected Configuration.LeftDataSource.Preprocessing.Deduplication.DeduplicationCondition deduplicationCondition;
                @XmlElement(name = "hashing-function", required = true)
                protected Configuration.LeftDataSource.Preprocessing.Deduplication.HashingFunction hashingFunction;
                @XmlElement(name = "minus-file", required = true)
                protected Configuration.LeftDataSource.Preprocessing.Deduplication.MinusFile minusFile;
                @XmlElement(name = "dedupe-file", required = true)
                protected Configuration.LeftDataSource.Preprocessing.Deduplication.DedupeFile dedupeFile;

                /**
                 * Gets the value of the deduplicationCondition property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Configuration.LeftDataSource.Preprocessing.Deduplication.DeduplicationCondition }
                 *     
                 */
                public Configuration.LeftDataSource.Preprocessing.Deduplication.DeduplicationCondition getDeduplicationCondition() {
                    return deduplicationCondition;
                }

                /**
                 * Sets the value of the deduplicationCondition property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Configuration.LeftDataSource.Preprocessing.Deduplication.DeduplicationCondition }
                 *     
                 */
                public void setDeduplicationCondition(Configuration.LeftDataSource.Preprocessing.Deduplication.DeduplicationCondition value) {
                    this.deduplicationCondition = value;
                }

                /**
                 * Gets the value of the hashingFunction property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Configuration.LeftDataSource.Preprocessing.Deduplication.HashingFunction }
                 *     
                 */
                public Configuration.LeftDataSource.Preprocessing.Deduplication.HashingFunction getHashingFunction() {
                    return hashingFunction;
                }

                /**
                 * Sets the value of the hashingFunction property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Configuration.LeftDataSource.Preprocessing.Deduplication.HashingFunction }
                 *     
                 */
                public void setHashingFunction(Configuration.LeftDataSource.Preprocessing.Deduplication.HashingFunction value) {
                    this.hashingFunction = value;
                }

                /**
                 * Gets the value of the minusFile property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Configuration.LeftDataSource.Preprocessing.Deduplication.MinusFile }
                 *     
                 */
                public Configuration.LeftDataSource.Preprocessing.Deduplication.MinusFile getMinusFile() {
                    return minusFile;
                }

                /**
                 * Sets the value of the minusFile property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Configuration.LeftDataSource.Preprocessing.Deduplication.MinusFile }
                 *     
                 */
                public void setMinusFile(Configuration.LeftDataSource.Preprocessing.Deduplication.MinusFile value) {
                    this.minusFile = value;
                }

                /**
                 * Gets the value of the dedupeFile property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Configuration.LeftDataSource.Preprocessing.Deduplication.DedupeFile }
                 *     
                 */
                public Configuration.LeftDataSource.Preprocessing.Deduplication.DedupeFile getDedupeFile() {
                    return dedupeFile;
                }

                /**
                 * Sets the value of the dedupeFile property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Configuration.LeftDataSource.Preprocessing.Deduplication.DedupeFile }
                 *     
                 */
                public void setDedupeFile(Configuration.LeftDataSource.Preprocessing.Deduplication.DedupeFile value) {
                    this.dedupeFile = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;attribute name="file" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class DedupeFile {

                    @XmlAttribute(name = "file")
                    protected String file;

                    /**
                     * Gets the value of the file property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getFile() {
                        return file;
                    }

                    /**
                     * Sets the value of the file property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setFile(String value) {
                        this.file = value;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="condition" maxOccurs="unbounded">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="params" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                 &lt;/sequence>
                 *                 &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *                 &lt;attribute name="column" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *                 &lt;attribute name="weight" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *       &lt;attribute name="acceptance-level" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "condition"
                })
                public static class DeduplicationCondition {

                    @XmlElement(required = true)
                    protected List<Configuration.LeftDataSource.Preprocessing.Deduplication.DeduplicationCondition.Condition> condition;
                    @XmlAttribute(name = "acceptance-level")
                    protected Integer acceptanceLevel;

                    /**
                     * Gets the value of the condition property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the condition property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getCondition().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link Configuration.LeftDataSource.Preprocessing.Deduplication.DeduplicationCondition.Condition }
                     * 
                     * 
                     */
                    public List<Configuration.LeftDataSource.Preprocessing.Deduplication.DeduplicationCondition.Condition> getCondition() {
                        if (condition == null) {
                            condition = new ArrayList<Configuration.LeftDataSource.Preprocessing.Deduplication.DeduplicationCondition.Condition>();
                        }
                        return this.condition;
                    }

                    /**
                     * Gets the value of the acceptanceLevel property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *     
                     */
                    public Integer getAcceptanceLevel() {
                        return acceptanceLevel;
                    }

                    /**
                     * Sets the value of the acceptanceLevel property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *     
                     */
                    public void setAcceptanceLevel(Integer value) {
                        this.acceptanceLevel = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="params" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *       &lt;/sequence>
                     *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *       &lt;attribute name="column" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *       &lt;attribute name="weight" type="{http://www.w3.org/2001/XMLSchema}int" />
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "params"
                    })
                    public static class Condition {

                        @XmlElement(required = true)
                        protected String params;
                        @XmlAttribute(name = "class")
                        protected String clazz;
                        @XmlAttribute(name = "column")
                        protected String column;
                        @XmlAttribute(name = "weight")
                        protected Integer weight;

                        /**
                         * Gets the value of the params property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getParams() {
                            return params;
                        }

                        /**
                         * Sets the value of the params property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setParams(String value) {
                            this.params = value;
                        }

                        /**
                         * Gets the value of the clazz property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getClazz() {
                            return clazz;
                        }

                        /**
                         * Sets the value of the clazz property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setClazz(String value) {
                            this.clazz = value;
                        }

                        /**
                         * Gets the value of the column property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getColumn() {
                            return column;
                        }

                        /**
                         * Sets the value of the column property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setColumn(String value) {
                            this.column = value;
                        }

                        /**
                         * Gets the value of the weight property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link Integer }
                         *     
                         */
                        public Integer getWeight() {
                            return weight;
                        }

                        /**
                         * Sets the value of the weight property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link Integer }
                         *     
                         */
                        public void setWeight(Integer value) {
                            this.weight = value;
                        }

                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;attribute name="columns" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="hash" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class HashingFunction {

                    @XmlAttribute(name = "columns")
                    protected String columns;
                    @XmlAttribute(name = "hash")
                    protected String hash;

                    /**
                     * Gets the value of the columns property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getColumns() {
                        return columns;
                    }

                    /**
                     * Sets the value of the columns property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setColumns(String value) {
                        this.columns = value;
                    }

                    /**
                     * Gets the value of the hash property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getHash() {
                        return hash;
                    }

                    /**
                     * Sets the value of the hash property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setHash(String value) {
                        this.hash = value;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;attribute name="file" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class MinusFile {

                    @XmlAttribute(name = "file")
                    protected String file;

                    /**
                     * Gets the value of the file property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getFile() {
                        return file;
                    }

                    /**
                     * Sets the value of the file property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setFile(String value) {
                        this.file = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="column" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="empty-values" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="params" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="column" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="converter" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "column"
        })
        public static class RowModel {

            @XmlElement(required = true)
            protected List<Configuration.LeftDataSource.RowModel.Column> column;

            /**
             * Gets the value of the column property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the column property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getColumn().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Configuration.LeftDataSource.RowModel.Column }
             * 
             * 
             */
            public List<Configuration.LeftDataSource.RowModel.Column> getColumn() {
                if (column == null) {
                    column = new ArrayList<Configuration.LeftDataSource.RowModel.Column>();
                }
                return this.column;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="empty-values" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="params" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *       &lt;attribute name="column" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="converter" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "emptyValues",
                "params"
            })
            public static class Column {

                @XmlElement(name = "empty-values", required = true)
                protected String emptyValues;
                @XmlElement(required = true)
                protected String params;
                @XmlAttribute(name = "column")
                protected String column;
                @XmlAttribute(name = "converter")
                protected String converter;
                @XmlAttribute(name = "name")
                protected String name;

                /**
                 * Gets the value of the emptyValues property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEmptyValues() {
                    return emptyValues;
                }

                /**
                 * Sets the value of the emptyValues property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEmptyValues(String value) {
                    this.emptyValues = value;
                }

                /**
                 * Gets the value of the params property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getParams() {
                    return params;
                }

                /**
                 * Sets the value of the params property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setParams(String value) {
                    this.params = value;
                }

                /**
                 * Gets the value of the column property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getColumn() {
                    return column;
                }

                /**
                 * Sets the value of the column property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setColumn(String value) {
                    this.column = value;
                }

                /**
                 * Gets the value of the converter property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getConverter() {
                    return converter;
                }

                /**
                 * Sets the value of the converter property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setConverter(String value) {
                    this.converter = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

            }

        }

    }

}
