//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.15 at 07:23:39 AM EDT 
//


package org.mitre.ptmatchadapter.fril.config;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Configuration }
     * 
     */
    public Configuration createConfiguration() {
        return new Configuration();
    }

    /**
     * Create an instance of {@link Configuration.LeftDataSource }
     * 
     */
    public Configuration.LeftDataSource createConfigurationLeftDataSource() {
        return new Configuration.LeftDataSource();
    }

    /**
     * Create an instance of {@link Configuration.LeftDataSource.Preprocessing }
     * 
     */
    public Configuration.LeftDataSource.Preprocessing createConfigurationLeftDataSourcePreprocessing() {
        return new Configuration.LeftDataSource.Preprocessing();
    }

    /**
     * Create an instance of {@link Configuration.LeftDataSource.Preprocessing.Deduplication }
     * 
     */
    public Configuration.LeftDataSource.Preprocessing.Deduplication createConfigurationLeftDataSourcePreprocessingDeduplication() {
        return new Configuration.LeftDataSource.Preprocessing.Deduplication();
    }

    /**
     * Create an instance of {@link Configuration.LeftDataSource.Preprocessing.Deduplication.DeduplicationCondition }
     * 
     */
    public Configuration.LeftDataSource.Preprocessing.Deduplication.DeduplicationCondition createConfigurationLeftDataSourcePreprocessingDeduplicationDeduplicationCondition() {
        return new Configuration.LeftDataSource.Preprocessing.Deduplication.DeduplicationCondition();
    }

    /**
     * Create an instance of {@link Configuration.LeftDataSource.RowModel }
     * 
     */
    public Configuration.LeftDataSource.RowModel createConfigurationLeftDataSourceRowModel() {
        return new Configuration.LeftDataSource.RowModel();
    }

    /**
     * Create an instance of {@link Configuration.LeftDataSource.Params }
     * 
     */
    public Configuration.LeftDataSource.Params createConfigurationLeftDataSourceParams() {
        return new Configuration.LeftDataSource.Params();
    }

    /**
     * Create an instance of {@link Configuration.LeftDataSource.Preprocessing.Deduplication.HashingFunction }
     * 
     */
    public Configuration.LeftDataSource.Preprocessing.Deduplication.HashingFunction createConfigurationLeftDataSourcePreprocessingDeduplicationHashingFunction() {
        return new Configuration.LeftDataSource.Preprocessing.Deduplication.HashingFunction();
    }

    /**
     * Create an instance of {@link Configuration.LeftDataSource.Preprocessing.Deduplication.MinusFile }
     * 
     */
    public Configuration.LeftDataSource.Preprocessing.Deduplication.MinusFile createConfigurationLeftDataSourcePreprocessingDeduplicationMinusFile() {
        return new Configuration.LeftDataSource.Preprocessing.Deduplication.MinusFile();
    }

    /**
     * Create an instance of {@link Configuration.LeftDataSource.Preprocessing.Deduplication.DedupeFile }
     * 
     */
    public Configuration.LeftDataSource.Preprocessing.Deduplication.DedupeFile createConfigurationLeftDataSourcePreprocessingDeduplicationDedupeFile() {
        return new Configuration.LeftDataSource.Preprocessing.Deduplication.DedupeFile();
    }

    /**
     * Create an instance of {@link Configuration.LeftDataSource.Preprocessing.Deduplication.DeduplicationCondition.Condition }
     * 
     */
    public Configuration.LeftDataSource.Preprocessing.Deduplication.DeduplicationCondition.Condition createConfigurationLeftDataSourcePreprocessingDeduplicationDeduplicationConditionCondition() {
        return new Configuration.LeftDataSource.Preprocessing.Deduplication.DeduplicationCondition.Condition();
    }

    /**
     * Create an instance of {@link Configuration.LeftDataSource.RowModel.Column }
     * 
     */
    public Configuration.LeftDataSource.RowModel.Column createConfigurationLeftDataSourceRowModelColumn() {
        return new Configuration.LeftDataSource.RowModel.Column();
    }

    /**
     * Create an instance of {@link Configuration.LeftDataSource.Params.Param }
     * 
     */
    public Configuration.LeftDataSource.Params.Param createConfigurationLeftDataSourceParamsParam() {
        return new Configuration.LeftDataSource.Params.Param();
    }

}
